### ISSUE TITLE
Support for Bibtex ‘file’ keys

### ISSUE THREAD

**Issue by eigengrau** [jkitchin/jmax#27]
Currently, org-ref allows opening PDF documents for bibkeys if there exists a PDF that bears the name of the bibkey.

Some citation managers actually export a file location along with the bibtex entry. While the `file` key is afaik not an official bibtex key, both Zotero and Jabref seem to use a standard syntax for this key (and I once read Medeley is also using this syntax, though I cannot ascertain that). It would be useful if org-ref could check for this key and open the PDF from there.

One caveat is that the `file` key allows supplying multiple files, so a heuristics would have to given to select a file if more than one is found. Likely, this could mean just selecting the first PDF document in the list.

The exact syntax seems to be the following:
```
file = {description1:absolute-path:mime-type; description2:absolute-path:mime-type; …}
```

E.g.:
```
@article{lasersohn1999pragmatichalos,
…
file = {Lasersohn - 1999 - Pragmatic halos.pdf:/home/seb/Owncloud/zotero/storage/B5MEFRMN/Lasersohn - 1999 - Pragmatic halos.pdf:application/pdf;Snapshot:/home/seb/.mozilla/firefox/nw2x3i1i.default/zotero/storage/NNZA96NS/417059.html:text/html}
}
```

**Comment by jkitchin** [comment]
I am closing this issue. You can define a function and set org-ref-open-pdf-function to do this. See the documentation for that variable, and the default function definition to see how to use it.
