### ISSUE TITLE
org-ref-insert-ref-link does not seem to work with figure labels

### ISSUE THREAD

**Issue by icymist** [jkitchin/jmax#41]
org-ref-insert-ref-link does not seem to work (labels are not prompted) with figure labels.

For example, org-ref-insert-ref-link works (labels are prompted) to insert the reference for the table below, but not for any of the figures. Only the figure with the explicit \label works.

I am on Emacs 24.3.1 and Org mode 8.2.10.

A minimum example to replicate the behavior is below:

```
None of the references seem to work below except for the table [[ref:tab:table1]] and the figure with the explicit \label{} [[ref:fig:explicit-label]].

#+CAPTION: Table
#+NAME: tab:table1
| a | b |
| 1 | 2 |
| 3 | 4 |
| 5 | 6 |

#+CAPTION: Cap1
#+NAME: fig:org-name
\label{fig:explicit-label}
[[file:supporting_information/scripts/inkscape.png]]

#+CAPTION: Cap1
#+NAME: fig:org-name
[[file:supporting_information/scripts/inkscape.png]]

#+CAPTION: Cap1
#+ATTR_LaTeX: :width 18cm
#+NAME: fig:org-name-attr
[[file:supporting_information/scripts/inkscape.png]]

#+CAPTION: Cap1
#+ATTR_LaTeX: :width 18cm
#+LABEL: fig:org-label-attr
[[file:supporting_information/scripts/inkscape.png]]

#+CAPTION: Cap1
#+ATTR_LaTeX: :width 18cm
#+NAME: fig:org-name-label-attr
#+LABEL: fig:org-name-label-attr
[[file:supporting_information/scripts/inkscape.png]]
```

**Comment by gongzhitaao** [comment]
I think I ran into a similar problem.
My problem is that the org-ref *does* find links to figures, however, it renders the link with `font-lock-warning-face` instead of `org-ref-ref-face`.  When you place the cursor on the `ref:fig:org-name`, it will show correctly the reference position.

```org
None of the references seem to work below except for the table ref:tab:table1
and the figure with the explicit ref:fig:org-name.

#+CAPTION: Table
#+NAME: tab:table1
| a | b |
| 1 | 2 |
| 3 | 4 |
| 5 | 6 |

#+CAPTION: Cap1
#+NAME: fig:org-name
[[file:supporting_information/scripts/inkscape.png]]
```
Renders as
![tmp](https://user-images.githubusercontent.com/704995/36431991-ab438978-161e-11e8-99ed-82aff782831a.png)

**Comment by jkitchin** [comment]
This is probably fixed in the org-ref repo. I am not updating jmax anymore. It is a little baffling that tables work and figures don't, as the issue seemed related to a case sensitive search on the #+NAMEs!

**Comment by gongzhitaao** [comment]
> issue seemed related to a case sensitive search on the #+NAMEs!

You are right, downcase from `#+NAME` to `#+name` solves the issue :rofl: 

Actually, I should have submitted this issue to the org-ref repo.  My org-ref version is 1.1.1, and it still has this issue.

**Comment by jkitchin** [comment]
you will have to update the org-ref git repo. I haven't pushed the update to scimax yet. It might be a week before I do that. I am in the middle of something else right now.
