### ISSUE TITLE
Issues with "pydoc httplib"

### ISSUE THREAD

**Issue by patxoca** [jkitchin/jmax#42]
I discovered pydoc.el a couple of days ago, its great! No contrived setup, works out of the box, useful ... very nice idea.

I've been playing with it a bit and I've found a couple of issues, they are not specific to httplib docs but this way you can reproduce the errors.

* Executing `pydoc httplib` fails with:

  >  pydoc-make-url-links: Search failed: "http://httplib:"

  Changing the regex on line 59 to `https?:` seems to solve the issue.

* Python 2.x old style classes are not *linkified*, btw `class HTTP`, `class HTTPConnection` etc. The problem is the regex used to identify classes, it expects a list of parent classes in parentheses. This will affect python 3.x classes too.

* Executing `pydoc httplib.SomeClass` does not *linkify* the methods, in this case the problem is the number of spaces on the left side of the vertical bar.

**Comment by jkitchin** [comment]
These are mostly fixed now. I found a better solution to the https? code I think: goto-address-mode. I think bullet 2 is fixed, and I think bullet 3 is fixed. Thanks for the report.
