### ISSUE TITLE
make pydoc a bit lazier

### ISSUE THREAD

**Issue by patxoca** [jkitchin/jmax#43]
More an annoyance than a real issue: in order to be able to lazzy-load pydoc it would be nice to have the pydoc function tagged with `;;;###autoload`. On the opposite side, pydoc uses functions from org. If org is not already loaded emacs will complain. In order to make it more modular I think that it should `require`explicitly external dependencies.

**Comment by jkitchin** [comment]
It doesn't need the org-dependency. I just copied that map for convenience. org is always loaded for me ;) I am changing it to text-mode-map. The map isn't even necessary, it is just to add some key-bindings. what do you think?

I saw the autoload code in your clone, and added that too.

**Comment by patxoca** [comment]
Not sure what *org map* you're referring to, I was talking about `org-src-font-lock-fontify-block`.

I think that having a keymap may be useful. Imagine having keys for commands like `goto-next-method`, `goto-next-class`, `search-method` etc. That would allow for quick access to the relevant topic within a pydoc *document*.

**Comment by jkitchin** [comment]
true enough, I forgot that one. I added some code at the top to require org if it is not loaded. thanks.
