### ISSUE TITLE
Strange pydoc behavior

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#44]
Hi John,

I guess pydoc might be a work in progress, but here are a couple of things that don't work for me (atleast on yosemite, emacs 24.4 and canopy).

1. I sometimes am unable to open the documentation by clicking the links, but I can open them by entering the full module path. For e.g.,
If I open pydoc on numpy and click linalg, it says module not found, but I can open numpy.linalg without problems. However clicking random from numpy seems to work fine.

2. The back button seems to behave weirdly sometimes. If I click back on numpy.linalg, go back back to numpy, click random, and finally click back, it goes to linalg and not numpy.

Also, it might be convenient to be able to click enter on the links instead of clicking on them and have a keyboard shortcut for back. ;) 

That being said, pydoc seems to be an awesome addition to jmax. Prevents me from opening the browser all the time!

**Comment by prtkm** [comment]
Actually the behavior for point 1 is a little more complicated. It seems that pydoc wants to open .linalg from the link and not numpy.linalg. 

![screen shot 2015-01-09 at 10 07 52 pm](https://cloud.githubusercontent.com/assets/2263899/5690263/3c657c8a-984c-11e4-9f72-640b6e0582be.png)

.random is actually the documentation for python's random module and not numpy.random! 

![screen shot 2015-01-09 at 10 10 08 pm](https://cloud.githubusercontent.com/assets/2263899/5690266/52cea44c-984c-11e4-84f5-d48f3dcc04ca.png)

If I now click back, and try to go to linalg, it wants to open random.linalg.

![screen shot 2015-01-09 at 10 14 34 pm](https://cloud.githubusercontent.com/assets/2263899/5690284/24b50e38-984d-11e4-807d-2508f86f6c1a.png)

Surprisingly, this does not happen for matplotlib.
![screen shot 2015-01-09 at 10 11 58 pm](https://cloud.githubusercontent.com/assets/2263899/5690274/95085e3e-984c-11e4-9de7-4068c1635ad7.png)

**Comment by jkitchin** [comment]
Thanks. I fixed the link issues.

the back link is a work in progress. I had in mind something like a history ring, but that is trickier to implement than I imagined.
