### ISSUE TITLE
load-theme: Unable to find theme file for `leuven'

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#45]
I get the following error when attempting to load emacs from anywhere but Gilgamesh. Error occurs right after user files are finished loading.

**Comment by jboes** [comment]
Used Emacs 24.4 as recommended by Prateek.

**Comment by prtkm** [comment]
M-x list-packages

leuven-theme >> install.

Or use emacs 24.4.

**Comment by jkitchin** [comment]
oh yeah. 24.4 is practically required now ;)

I should make that more obvious.

Jacob Boes writes:

> Used Emacs 24.4 as recommended by Prateek.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/45#issuecomment-69657987

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
