### ISSUE TITLE
Weird org message

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#46]
Hi John, 

I often get this cryptic emacs message when running code blocks,

executing Python code block...
Wrote /tmp/babel-14636JZ/ob-input-14637DW
Code block evaluation complete.
org-display-inline-images: Invalid image specification

Everything seems to work fine, and it doesn't seem to do anything as far as I can tell, but its weird that it shows up.

Prateek

**Comment by jkitchin** [comment]
does it by chance happen in org files with no images?

I added a hook here:
https://github.com/jkitchin/jmax/blob/master/jmax-org.el#L502

to display images after running a code block. That way I don't have to
do it manually.

Prateek Mehta writes:

> Hi John,
>
> I often get this cryptic emacs message when running code blocks,
>
> executing Python code block...
> Wrote /tmp/babel-14636JZ/ob-input-14637DW
> Code block evaluation complete.
> org-display-inline-images: Invalid image specification
>
> Everything seems to work fine, and it doesn't seem to do anything as far as I can tell, but its weird that it shows up.
>
> Prateek
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/46

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
The file has images, and all images were already being displayed inline
before the code block ran.

I tested the behavior a little more.

1. Ran org-remove-inline images, then ran the code. Seems to work fine and
display all images after execution.

2. If all images are displayed inline, and I run the code, I get the
message.

3. If all images before the code are displayed inline and there is an image
after the code not being displayed, I still get the message.

Maybe you should do something like,

(org-remove-inline-images)
(org-display-inline-images)

to get the images to refresh after each code block.

Prateek

**Comment by jkitchin** [comment]
did you try that and see that it gets rid of the message?

Prateek Mehta writes:

> The file has images, and all images were already being displayed inline
> before the code block ran.
>
> I tested the behavior a little more.
>
> 1. Ran org-remove-inline images, then ran the code. Seems to work fine and
> display all images after execution.
>
> 2. If all images are displayed inline, and I run the code, I get the
> message.
>
> 3. If all images before the code are displayed inline and there is an image
> after the code not being displayed, I still get the message.
>
> Maybe you should do something like,
>
> (org-remove-inline-images)
> (org-display-inline-images)
>
> to get the images to refresh after each code block.
>
> Prateek
>
>
> On Fri, Jan 16, 2015 at 6:04 PM, John Kitchin <notifications@github.com>
> wrote:
>
>> does it by chance happen in org files with no images?
>>
>> I added a hook here:
>> https://github.com/jkitchin/jmax/blob/master/jmax-org.el#L502
>>
>> to display images after running a code block. That way I don't have to
>> do it manually.
>>
>> Prateek Mehta writes:
>>
>> > Hi John,
>> >
>> > I often get this cryptic emacs message when running code blocks,
>> >
>> > executing Python code block...
>> > Wrote /tmp/babel-14636JZ/ob-input-14637DW
>> > Code block evaluation complete.
>> > org-display-inline-images: Invalid image specification
>> >
>> > Everything seems to work fine, and it doesn't seem to do anything as far
>> as I can tell, but its weird that it shows up.
>> >
>> > Prateek
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/jkitchin/jmax/issues/46
>>
>> --
>> Professor John Kitchin
>> Doherty Hall A207F
>> Department of Chemical Engineering
>> Carnegie Mellon University
>> Pittsburgh, PA 15213
>> 412-268-7803
>> @johnkitchin
>> http://kitchingroup.cheme.cmu.edu
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jkitchin/jmax/issues/46#issuecomment-70337177>.
>>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/46#issuecomment-70340836

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
I hadn't when I wrote the last message, but I tried it now, and it looks
like the message is gone!

I did something like this.

;; refresh images after running a block
(defun org-refresh-images ()
  (interactive)
  (org-remove-inline-images)
  (org-display-inline-images))

(add-hook 'org-babel-after-execute-hook
  (lambda () (org-refresh-images)))

**Comment by jkitchin** [comment]
ok. I pushed this code in.

**Comment by prtkm** [comment]
Thanks!
