### ISSUE TITLE
Broken: agenda view options "j" and "J"

### ISSUE THREAD

**Issue by atunanggara** [jkitchin/jmax#47]
This is my first week of using org-mode and emacs all together, so there might just be a simple solution for this issue that I am not seeing. I noticed the "j" and "J" commands for agenda were not working for me when I tried integrating jmax version of org-mode with MobileOrg using [this setup](http://mobileorg.ncogni.to/doc/getting-started/using-dropbox/). My bandaid approach right now is to comment out line 283-289 of jmax-org.el to get MobileOrg to play well with my org-mode setup.

**Comment by jkitchin** [comment]
That is the right thing to have done. I just took out that section, they were just my personal setup.

**Comment by atunanggara** [comment]
Thanks for the replies!
