### ISSUE TITLE
helm-bibtex error

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#49]
I'm getting the following error when attempting to load emacs from my linux machine:

For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output) [3 times]
Importing package-keyring.gpg...done
Contacting host: jorgenschaefer.github.io:80
Loading /home-research/jboes/boes-python/jmax/elpa/helm-20150107.308/helm-autoloads.el (source)...done
ad-handle-definition: `tramp-read-passwd' got redefined
Loading /home-research/jboes/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Loading /home-research/jboes/boes-python/jmax/email.el (source)...done
Loading /home-research/jboes/boes-python/jmax/matlab/matlab-load.el (source)...done
Loading /home-research/jboes/boes-python/jmax/jmax-org.el (source)...
Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...
Starting new Ispell process /usr/bin/aspell with default dictionary...
Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...done
Loaded /home-research/jboes/boes-python/jmax/org/org-show.el
Loading /home-research/jboes/boes-python/jmax/org-ref/org-ref.el (source)...
eval-buffer: Cannot open load file: no such file or directory, helm-bibtex

**Comment by jkitchin** [comment]
True enough.

M-x package-install helm-bibtex

I will fix that tomorrow.

On January 24, 2015, at 8:51 PM, Jacob Boes <notifications@github.com> wrote:

I'm getting the following error when attempting to load emacs from my linux machine:

For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output) [3 times]
Importing package-keyring.gpg...done
Contacting host: jorgenschaefer.github.io:80
Loading /home-research/jboes/boes-python/jmax/elpa/helm-20150107.308/helm-autoloads.el (source)...done
ad-handle-definition: `tramp-read-passwd' got redefined
Loading /home-research/jboes/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Loading /home-research/jboes/boes-python/jmax/email.el (source)...done
Loading /home-research/jboes/boes-python/jmax/matlab/matlab-load.el (source)...done
Loading /home-research/jboes/boes-python/jmax/jmax-org.el (source)...
Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...
Starting new Ispell process /usr/bin/aspell with default dictionary...
Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...done
Loaded /home-research/jboes/boes-python/jmax/org/org-show.el
Loading /home-research/jboes/boes-python/jmax/org-ref/org-ref.el (source)...
eval-buffer: Cannot open load file: no such file or directory, helm-bibtex

**Comment by jkitchin** [comment]
I think this will fix itself now.

Jacob Boes writes:

> I'm getting the following error when attempting to load emacs from my linux machine:
>
> For information about GNU Emacs and the GNU system, type C-h C-a.
> (Shell command succeeded with no output) [3 times]
> Importing package-keyring.gpg...done
> Contacting host: jorgenschaefer.github.io:80
> Loading /home-research/jboes/boes-python/jmax/elpa/helm-20150107.308/helm-autoloads.el (source)...done
> ad-handle-definition: `tramp-read-passwd' got redefined
> Loading /home-research/jboes/.emacs.d/recentf...done
> Cleaning up the recentf list...done (0 removed)
> Loading /home-research/jboes/boes-python/jmax/email.el (source)...done
> Loading /home-research/jboes/boes-python/jmax/matlab/matlab-load.el (source)...done
> Loading /home-research/jboes/boes-python/jmax/jmax-org.el (source)...
> Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...
> Starting new Ispell process /usr/bin/aspell with default dictionary...
> Loading /home-research/jboes/boes-python/jmax/org/org-show.el (source)...done
> Loaded /home-research/jboes/boes-python/jmax/org/org-show.el
> Loading /home-research/jboes/boes-python/jmax/org-ref/org-ref.el (source)...
> eval-buffer: Cannot open load file: no such file or directory, helm-bibtex
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/49

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jboes** [comment]
Works!
