### ISSUE TITLE
Helm doesn't allow multi-citation entry

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#50]
When using C-c ] to add citations to an org document, Helm prompts the user to press C-j to insert a citation while keeping the session (I assume the Helm session).

This opens the mini-buffer with an identical Helm session, but doesn't add any citation to the org document.

**Comment by jkitchin** [comment]
to get multiple citations, mark entries with C-spc, and then press
enter.

I am not sure what C-j is supposed to be doing. You can resume a helm
session with C-c h r


Jacob Boes writes:

> When using C-c ] to add citations to an org document, Helm prompts the user to press C-j to insert a citation while keeping the session (I assume the Helm session).
>
> This opens the mini-buffer with an identical Helm session, but doesn't add any citation to the org document.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/50

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jboes** [comment]
Thanks for the help
