### ISSUE TITLE
hi-lock- mode message

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#51]
Hi John,

I see this message after pulling the latest update of jmax. I was wondering if you also see it, or if it's because of something else I installed.

Warning (emacs): Possible archaic use of (hi-lock-mode).
Use (global-hi-lock-mode 1) in .emacs to enable hi-lock for all buffers,
use (hi-lock-mode 1) for individual buffers.  For compatibility with Emacs
versions before 22 use the following in your init file:

        (if (functionp 'global-hi-lock-mode)
            (global-hi-lock-mode 1)
          (hi-lock-mode 1))

**Comment by jkitchin** [comment]
I also see this. I guess it is from button-lock. It doesn't seem to cause any problems other than an annoying message. Solution. Do not close emacs ;)
