### ISSUE TITLE
Citation error on local linux machine

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#52]
My local machine is getting the following error when selecting cite links on my linux machine:

Error running timer `org-ref-link-message': (void-function reftex-get-bib-field)

I do not get the error on Gilgamesh.

**Comment by jkitchin** [comment]
That is pretty weird. Can you run this on your local machine: (require 'reftex-cite)

**Comment by jboes** [comment]
That fixed it. No idea how I un-required that.

**Comment by jkitchin** [comment]
me neither. It is required in org-ref.el already.
