### ISSUE TITLE
Themes don't work as expected

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#54]
Hi John,

I think one of your recent commits changed the way themes are loaded. I had a line (setq jmax-user-theme 'tangotango) in user/prateekm.el, which used to load the theme I wanted. Now the theme loading gets redefined in user.el. 

However, changing (setq jmax-user-theme 'leuven) in user.el (https://github.com/jkitchin/jmax/blob/master/user/user.example#L25) to any other theme does not seem to load the new theme. I had to add the lines

(disable-theme 'leuven)
(load-theme 'tangotango t)

for it to actually work.

Possible solutions are to maybe stop loading any theme at all in jmax.el, or restore the old behavior of (setq jmax-user-theme themename) (though I don't know how this would have changed).

**Comment by jkitchin** [comment]
you should probably delete user.el, or at least the junk in it you do not need, e.g. the theme. this file is not under vc in jmax.

I recently reorganized jmax for myself, which caused some of that behavior. I have moved the theme load to after the user code so it should be the same as before.

**Comment by prtkm** [comment]
Great. Looks like everything is back to normal.
