### ISSUE TITLE
Wrong type argument: stringp, nil after every python block execution

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#55]
Hi John,

With the latest jmax, I get this annoying message and a beep after every python block on both mac and linux. Any idea why its happening? It doesn't happen for sh blocks.

executing Python code block...
Wrote /var/folders/bv/yrjr0gsd49jbzzlr6kzblmj80000gn/T/babel-158732cx/ob-input-15873lZG
Code block evaluation complete.
and: Wrong type argument: stringp, nil

**Comment by jkitchin** [comment]
try a new pull. I added some stuff on stripping session output that was probably causing that.

**Comment by prtkm** [comment]
look like it works.
