### ISSUE TITLE
Flyspell error on linux.

### ISSUE THREAD

**Issue by gperaza** [jkitchin/jmax#57]
I get the following error with a fresh install:
"Error enabling Flyspell mode:\n%s" "(/usr/bin/aspell did not output version line)"
Closing emacs afterwards reveals a freezed process named "ispell" with the command : 
 /usr/bin/aspell -a -m -B --encoding=utf-8

**Comment by jkitchin** [comment]
is this a new error? That looks like an aspell error on your end.

**Comment by gperaza** [comment]
Flyspell was working before I tried jmax. Not loading org-show solves the error so I'm guessing it is related to how org-show handles flyspell. I'll try reading through org-show.el to try and isolate the problem. I am really a beginner with emacs lisp though, so maybe I'm missing something.

**Comment by prtkm** [comment]
(setq flyspell-issue-welcome-flag nil)
(add-hook 'org-mode-hook 'turn-on-flyspell 'append)

I remember putting something like this in my init file on one of my
machines. It seemed to fix it for me.

On Thu, May 14, 2015 at 10:32 AM, gperaza <notifications@github.com> wrote:

> Flyspell was working before I tried jmax. Not loading org-show solves the
> error so I'm guessing it is related to how org-show handles flyspell. I'll
> try reading through org-show.el to try and isolate the problem. I am really
> a beginner with emacs lisp though, so maybe I'm missing something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/jmax/issues/57#issuecomment-102053209>.
>



-- 
Prateek Mehta
Chemical Engineering PhD Student
University of Notre Dame
(412) 417-0152

**Comment by jkitchin** [comment]
@gperaza does the fix above solve your problem too?

**Comment by gperaza** [comment]
I doesn't fix it. I will disable org-show for now.

**Comment by prtkm** [comment]
In my case, I still get the message on startup, but flyspell still seems to
work as expected for org files...

On Wed, May 20, 2015 at 1:41 PM, gperaza <notifications@github.com> wrote:

> I doesn't fix it. I will disable org-show for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/jmax/issues/57#issuecomment-103971233>.
>



-- 
Prateek Mehta
Chemical Engineering PhD Student
University of Notre Dame
(412) 417-0152

**Comment by jkitchin** [comment]
weird. I don't see any such warnings. org-show does store a variable about
whether flyspell is enabled. I think there might be a bug there. I pushed a
little change now that might fix it. let me know if it helps.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Your fix removes the message for me if flyspell is not called on initialization.

If I add a hook (add-hook 'org-mode-hook 'flyspell-mode) in my init files, it doesn't show up a red hat machine I use, but does on my debian machine. I think it is more of a aspell/emacs bug than a jmax bug. It seems to be a fairly common... 

https://github.com/bbatsov/prelude/issues/729
https://github.com/purcell/emacs.d/issues/73
