### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by P-Mercator** [jkitchin/jmax#62]
Hello,

I am new to emacs world and so I am scratching my head when I get the error message in the middle of package install:

Wrong type argument: arrayp, highlight-identation

I have cloned the whole jmax folder, installed emacs through homebrew (as instructed) and run emacs with the shell command for mac.
Any idea where that would be coming from?

Cheers!

**Comment by jkitchin** [comment]
That is a new one. Can you open packages.el in jmax and run:
M-x eval-buffer

does that work?

**Comment by Pierre-Stir** [comment]
Thank you for looking into it.

I am unable to evaluate packages.el. It throws the same error.

However, allow me to elaborate, as I have just retried the whole install.
The first error message I get (after a fresh git clone) is:

Symbol's value as variable is void: org-babel-safe-header-args

Any run after that and it throws the previous error.

**Comment by Pierre-Stir** [comment]
I found that error in an [older issue][https://github.com/jkitchin/org-ref/issues/48]

Loading /Users/pierre/Dropbox/Emacs/jmax/jmax-org.el (source)...
defconst: Symbol’s value as variable is void: org-babel-safe-header-args

So I ran the byte-compile file on ob-R.el

Compiling /Users/pierre/Dropbox/Emacs/jmax/elpa/org-plus-contrib-20150824/ob-R.el...done
Wrote /Users/pierre/Dropbox/Emacs/jmax/elpa/org-plus-contrib-20150824/ob-R.elc

But still the same error:

For information about GNU Emacs and the GNU system, type C-h C-a.
(Shell command succeeded with no output) [3 times]
ad-handle-definition: ‘ido-completing-read’ got redefined
Contacting host: jorgenschaefer.github.io:80
Package refresh done
package-install: Wrong type argument: arrayp, highlight-indentation

**Comment by jkitchin** [comment]
hmm.. lots of elpa problems these days. I tried pushing my org and highlight packages into jmax. try a new pull and let me know if it helps.

**Comment by jkitchin** [comment]
ok, I tried pushing a highlight-indentation package in. Canyou give it a try now?

**Comment by Pierre-Stir** [comment]
That seemed to have worked.

The last message I get is 

``
[yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
``

Is that anything I should worry about or would that be a success?
I have to mention that I haven't added any personalisation (such as bibtex, or else)

**Comment by jkitchin** [comment]
Great. The yas error is nothing to worry about.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu


On Thu, Aug 27, 2015 at 9:58 AM, Pierre Mercatoris <notifications@github.com

**Comment by Pierre-Stir** [comment]
That's great! Thank you very much!

I will now run through your instructions for customisation.

Best wishes
