### ISSUE TITLE
Language error when starting jmax on windows

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/jmax#63]
I receive an error when I start up emacs with jmax on windows with version 24.5.1. I haven't noticed any problems from this error.

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_ALL = (unset),
	LANG = "ENU"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

**Comment by jkitchin** [comment]
I saw this a lot last semester. it doesn't seem to cause any issues that i could see either.
