### ISSUE TITLE
cm-wdiff-git error

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#64]
Hi John,

The command is returning the following error:

```javascript
concat: Args out of range: "", 42, 43
```

I get the same error on my fresh install on my windows laptop as well.

Best,
Jake

**Comment by jkitchin** [comment]
do you have wdiff installed?

Jacob Boes writes:

> Hi John,
>
> The command is returning the following error:
>
> concat: Args out of range: "", 42, 43
>
> I get the same error on my fresh install on my windows laptop as well.
>
> Best,
> Jake
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jmax/issues/64

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jboes** [comment]
I didn't have wdiff installed, but I'm still getting the same error.

**Comment by jkitchin** [comment]
I pushed a fix to this I think.

On Thursday, January 21, 2016, Jacob Boes <notifications@github.com> wrote:

> I didn't have wdiff installed, but I'm still getting the same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/jmax/issues/64#issuecomment-173715055>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jboes** [comment]
Works great!
