### ISSUE TITLE
org-ref not automatically updating

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/jmax#65]
I believe org-ref is not automatically updating when using jmax. I first noticed this when opening emacs and not having an auto-update, even though I am aware of org-ref updates. 

Upon a fresh install of jmax, typing "git log" when I'm inside the org-ref folder gives me this as the most recent commit.

commit 1d7775b77d3041d08360136de6f7b9d3956af79b
Author: John Kitchin <jkitchin@andrew.cmu.edu>
Date:   Wed Feb 17 09:18:07 2016 -0500

    add new tests

Which I know is NOT the most recent commit on the org-ref github. Coincidentally, this is the same date as the most recent jmax commit. Could a jmax commit be required for a org-ref update?

**Comment by jkitchin** [comment]
the org-ref in jmax is not always up to date with the org-ref repo because it is a submodule. I have to commit a version of org-ref to jmax for it to update. I don't push all the changes in org-ref all the time, but it is due for an update soon.
