### ISSUE TITLE
Loss of syntax highlighting in org-mode upon update

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#70]
Hi John,

I updated jmax and all my emacs packages on OS X, but strangely I don't have syntax highlighting in org-mode code blocks anymore. If I do C-c ' to go into python mode the colors come back. Any idea why this is happening?

**Comment by jkitchin** [comment]
Are there any errors in messages?

On May 13, 2016, at 4:06 AM, Prateek Mehta <notifications@github.com> wrote:

Hi John,

I updated jmax and all my emacs packages on OS X, but strangely I don't have syntax highlighting in org-mode code blocks anymore. If I do C-c ' to go into python mode the colors come back. Any idea why this is happening?

**Comment by prtkm** [comment]
Reinstalling org fixed it.
