### ISSUE TITLE
prompts for updates twice

### ISSUE THREAD

**Issue by jboes** [jkitchin/jmax#72]
jmax will prompt the user to update 2 times if it is needed.

Setting (setq jmax-auto-update nil) in the users init file will only prevent one of these update requests, not the other.

**Comment by jkitchin** [comment]
I can't reproduce this. Does it stop after the second time?

**Comment by jboes** [comment]
Yes, and it will only prompt me once if (setq jmax-auto-update nil) is set.

**Comment by jboes** [comment]
I've noticed this message only appears once for the masters students as well, so I suspect there is something in my personal initialization file that is responsible.
