### ISSUE TITLE
org-babel-async-execute creates temp files

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jmax#73]
```
[pmehta1@dftfe:research]$ ls py*
py-11231G8c  py-1481HFI   py-17707Gil  py-18326RaQ  py-1895Ayk   py-19613gfe  py-20467_Bc  py-23716KQu  py-3300hYx  py-8096CWH
py-118651XA  py-15966WNW  py-183263FE  py-1895aGx   py-19271zKl  py-19613HFl  py-229736zq  py-28483cp   py-5009xqL
```

Hi John, 

Asynchronously running python code blocks seems to create these temporary files. Is it possible to add in a line that removes them once the code is done running?

Prateek

**Comment by jkitchin** [comment]
they should be getting deleted here: https://github.com/jkitchin/jmax/blob/master/jmax-org.el#L832

I guess these are left over from some runs that generated errors perhaps? If you delete these, do they still accumulate?

**Comment by jboes** [comment]
I can confirm that these don't seem to be deleting themselves, even when completed successfully.

**Comment by jkitchin** [comment]
weird. They disappear for me. Once there is an error though, they don't disappear. I don't know what would cause that though. One way is you start it again, before the previous one finished, then it fails, which seems to leave things behind. I pushed this https://github.com/jkitchin/jmax/commit/9cf2388fd4272ba8bdb9907ae49eb43757b576d4 to fix that issue. I am not sure why you would be seeing anything else though.

**Comment by prtkm** [comment]
I just realized that those files were probably remnants from me killing long running scripts explicitly from the terminal. I don't think there's a fix for that! 

Btw, is jmax officially moved to scimax now?

**Comment by jkitchin** [comment]
It depends on what "officially" means ;) scimax is all I am using, It has most things from jmax (i.e. everything I regularly need) but not everything. I haven't asked anyone else move to it yet.

**Comment by jboes** [comment]
I've updated jmax and tried this again. The files seem to be managing themselves correctly now.
