### ISSUE TITLE
overlay issue

### ISSUE THREAD

**Issue by zeltak** [jkitchin/jmax#75]
Hi John

thx again for another fantastic addition to the org eco system :)

i have started exploring using org-colored-text.el and its great. one thing that i saw in your original blog post and is kinda annoying is the overlay issue. has there been any progress with solving this? its especially bad if i use alot of these color links in sub sections (like 30-40 of them in each sub headers) and the the org file looks very messy :)

thx alot

Z

**Comment by jkitchin** [comment]
there won't be any progress on this until org-9.0 is the default available org. That has a rewritten link fontification engine that will make it possible to avoid using overlays.

**Comment by zeltak** [comment]
ahh ok got it. ill wait then to shift my colored text to org-colored-text when org 9 comes out. thx for all your work

best

Z

**Comment by zeltak** [comment]
orgmode 9.0 is out :)

http://orgmode.org/Changes.html

any plans on working on the overlay issue :D 

thx!

Z

**Comment by jkitchin** [comment]
This is all it takes now:

```
(require 's)
(defun color-comp (&optional arg)
  (let ((color-data (progn
		      (save-selected-window
			(list-colors-display))
		      (prog1
			  (with-current-buffer (get-buffer "*Colors*")
			    (mapcar (lambda (line)
				      (append (list line)
					      (s-split " " line t)))
				    (s-split "\n" (buffer-string))))
			(kill-buffer "*Colors*")))))
    (format "color:%s"
	    (s-trim (cadr (assoc (completing-read "Color: " color-data) color-data))))))
		   

(defun color-link-face (path)
  `(:foreground ,path))

(org-link-set-parameters "color"	     
			 :face 'color-link-face
			 :complete 'color-comp)
```

completion is works with C-c C-l.

**Comment by zeltak** [comment]
wow seems to work great :) thx so much

is it possible to define custom link colors, specifically some that have both a custom BG and FG

thx again for your work!

Z

**Comment by jkitchin** [comment]
certainly that is possible. you can make the face for the link anything you want. For example

```
(defun color-link-face (path)
  `(:foreground ,path :background "yellow"))
```

**Comment by zeltak** [comment]
thx, but im not sure im following. so if i want to add to the color: link types a color1 that has a FG:blue and BG: white and then a color2 with a FG:yellow and BG: red etc.. how would i define them in the above code snippet? and will they appear in the current color menu that pops up?

thx so much again

Z

**Comment by jkitchin** [comment]
You could do something like:

```
#+BEGIN_SRC emacs-lisp
(require 's)
(defvar org-link-colors '(("color1" . '(:foreground "blue"))
			  ("color2" . '(:foreground "red" :background "yellow"))))

(defun color-comp (&optional arg)
  (let ((color-data (progn
		      (save-selected-window
			(list-colors-display))
		      (append
		       (mapcar (lambda (cell)
				 (cons (propertize (car cell)
						   'face (cdr cell))
				       (list (car cell))))
			       org-link-colors)
		       (prog1
			   (with-current-buffer (get-buffer "*Colors*")
			     (mapcar (lambda (line)
				       (append (list line)
					       (s-split " " line t)))
				     (s-split "\n" (buffer-string))))
			 (kill-buffer "*Colors*"))))))
    (format "color:%s"
	    (s-trim (cadr (assoc (completing-read "Color: " color-data) color-data))))))


(defun color-link-face (path)
  (or (cdr (assoc path org-link-colors))
      `(:foreground ,path)))

(defun color-link-export (path description backend)
  (cond
    ((eq backend 'html)
     (let ((rgb (assoc (downcase path) color-name-rgb-alist))
       r g b)
       (if rgb
       (progn
         (setq r (* 255 (/ (nth 1 rgb) 65535.0))
           g (* 255 (/ (nth 2 rgb) 65535.0))
           b (* 255 (/ (nth 3 rgb) 65535.0)))
         (format "<span style=\"color: rgb(%s,%s,%s)\">%s</span>"
             (truncate r) (truncate g) (truncate b)
             (or description path)))
     (format "No Color RGB for %s" path))))))


(org-link-set-parameters "color"         
             :face 'color-link-face
             :complete 'color-comp
             :export 'color-link-export)
#+END_SRC```

**Comment by zeltak** [comment]
Perfect!

thx so much

Z
