### ISSUE TITLE
Problem with exporting to PDF

### ISSUE THREAD

**Issue by Gary-Chow** [jkitchin/jmax#77]
First, thank you very much for this great job. I am using your org-ref.

I am new in emacs, learning it tor org mode. I want to export scientific papers in org mode. I install jmax. But meet problems. Any suggestion? Thank you very much.

environment:
Ubuntu 14.04
Emacs 25.1
texlive

I install as below:
git clone https://github.com/jkitchin/jmax.git
emacs -q -l jmax/init.el
bash -c "$(curl -fsSL https://raw.githubusercontent.com/jkitchin/jmax/master/install-jmax-linux.sh)"
sudo tlmgr conf texmf TEXMFHOME "~/my/path/to/jmax/texmf"

test:
  example/technical-documents-in-org.org ---- unable to resolve link 'bibliography'
  example/cmu-article/example-article.org ---- pdf not produced
  example/cmu-phd-dissertation/dissertation.org ---- pdf not produced
  example/elsarticle/manuscript.org ---- pdf not produced

**Comment by jkitchin** [comment]
We use scimax now. http://github.com/jkitchin/scimax.

unable to resolve link 'bibliography suggests org-ref has not been loaded. How did you run the test?


It is basically the same as jmax, but it loads faster, is actively maintained.

**Comment by Gary-Chow** [comment]
I just install jmax, and try to export the examples in jmax. 

I see package-list in emacs showing org-ref not installed. After org-ref installed,  still have the "PDF not produced" problem.

Thank you for your new project-scimax. I will try it later.
