### ISSUE TITLE
Any way to include superscript at beginning of word in org-mode (technical document)

### ISSUE THREAD

**Issue by japhir** [jkitchin/jmax#80]
In your nice [guide to org-mode](https://github.com/jkitchin/jmax/blob/master/examples/technical-documents-in-org.org#subscripts-and-superscripts) you explain how to do superscript and subscript for a reproducible manuscript. This doesn't work for the beginning of a word, however `^{13}C`
The LaTeX workaround, of putting empty curly braces in front exports as actual curly braces: `{}^{13}C`

In the past I've used `mhchem` to solve this issue (`\ce{^13C}`) but often times, journals don't accept latex submissions with custom packages included.

Any idea how I can keep working in org-mode and still easily export to LaTeX for manuscript submission?

Maybe not really an issue, but I thought I'd ask :).

**Comment by japhir** [comment]
On a somewhat related note: how do you do units and spacing correctly without using `siunitx`? In a recent manuscript I had to write e.g.: `15\,kg`, or `15\,{\degree}C` in LaTeX, but I would hate to have to write `@@\,@@` between a value and its unit ([org-manual](https://orgmode.org/manual/Quoting-LaTeX-code.html#Quoting-LaTeX-code))

**Comment by japhir** [comment]
On a somewhat related note: how do you do units and spacing correctly without using `siunitx`? In a recent manuscript I had to write e.g.: `15\,kg`, or `15\,{\degree}C` in LaTeX, but I would hate to have to write `@@\,@@` between a value and its unit ([org-manual](https://orgmode.org/manual/Quoting-LaTeX-code.html#Quoting-LaTeX-code))

**Comment by jkitchin** [comment]
Here are some options that might work for you:


```
1. \nbsp^{13}C
2. \(^{13}\)C


Spacing


1. \(15\!\)kg 
2. 15 kg
3. \(15\,\)kg 
4. \(15\:\)kg 
5. \(15\;\)kg 
6. \(15\quad\)kg 
7. \(15\qquad\)kg 
```

**Comment by japhir** [comment]
Thanks a lot! I've decided to use custom entities in stead: https://github.com/japhir/ArchConfigs/blob/master/myinit.org#org-entities-user
mainly `\us{}` as "unit space", which just inserts `\,` in LaTeX, and `&nbsp;` in html.

**Comment by jkitchin** [comment]
That is also a good solution. Thanks for sharing it.
