### ISSUE TITLE
org-show gives an error

### ISSUE THREAD

**Issue by vikasrawal** [jkitchin/jmax#81]
When I try to start org-show (with the sample org-show.org), I get the following error:

org-show-start-slideshow: Wrong number of arguments: (0 . 1), 2

What could it be?

Vikas

**Comment by jkitchin** [comment]
If I had to guess, it is because of something related to tags. I have not kept jmax up to date, so the org-show there may be out of date compared to the one in scimax (https://github.com/jkitchin/scimax/tree/master/org-show)

**Comment by vikasrawal** [comment]
May I bother you with a more fundamental problem I have.

I really like many things in scimax: for example, org-ref, ov-highlighter, and org-show. However, I do not use many things (for example, python). 

I use prelude to configure my emacs. I would like to integrate scimax into prelude, and be able to use what I need. I did this by forking scimax (scimaxmin repo in my github), removing things that I did not need, and integrating it into my prelude. But keeping up my branch with the upstream repo has become difficult since you have modified many things in scimax.

Do you think my approach -- to fork and create a leaner branch of scimax -- the right way to go? Or would you have some other advice?

Thanks a lot for making all these wonderful tools available.

**Comment by jkitchin** [comment]
What I would do is use `use-package` like this:

```
(use-package org-ref-arxiv
  :ensure nil
  :load-path (lambda () (expand-file-name "org-ref" scimax-dir)))
```

This way you can just keep a scimax directory around, don't change anything in it, except when you want to update it, and just load whatever packages you want from it.

**Comment by vikasrawal** [comment]
Thanks. That works beautifully.

Vikas
